-- Seed Initial 186 Providers for Supabase PostgreSQL
INSERT INTO public.providers (id, name, category_id, neighborhood_id, specialty, description, phone, whatsapp, email, website, address, languages, is_verified, rating, reviews_count, tags, source_badge, source_channel, source_uploaded_at, contributor_masked, contributor_revealed, reliability_score, original_notes, source_sheet) VALUES
  ('it_tech_mac_clinic', 'Mac Clinic Nairobi', 'it_tech', 'westlands', 'Centre certifié Apple, réparations logiques & écrans Retina', 'Spécialiste agréé Mac, MacBook Pro/Air, iMac et iPad. Remplacement de batteries, claviers, cartes mères et récupération de données.', '+254 722 000 111', '+254722000111', 'support@macclinic.co.ke', 'https://macclinic.co.ke', 'Westlands Commercial Centre, Ring Rd Parklands, Nairobi', '{"Français", "Anglais"}', TRUE, 4.9, 28, '{"it_tech", "westlands", "Apple", "MacBook", "iMac", "iPad", "Réparation", "Écran"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-02T10:00:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Service rapide et pièces officielles.', 'IT Tech'),
  ('it_tech_irepairs', 'iRepairs Kenya (iPhone & Android)', 'it_tech', 'westlands', 'Dépannage express smartphones, écrans OLED & connecteurs de charge', 'Réparation express en 45 min pour smartphones toutes marques (iPhone, Samsung Galaxy, Google Pixel, Xiaomi). Changement vitres et batteries neuves.', '+254 711 222 333', '+254711222333', 'contact@irepairs.co.ke', 'https://irepairs.co.ke', 'Sarit Centre, 2nd Floor, Westlands, Nairobi', '{"Français", "Anglais"}', TRUE, 4.8, 19, '{"it_tech", "westlands", "iPhone", "Samsung", "Smartphone", "Écran", "Batterie", "Express"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-02T10:00:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Très efficace au Sarit Centre.', 'IT Tech'),
  ('it_tech_david', 'David Tech Support (Réseaux Wi-Fi & PC)', 'it_tech', 'lavington', 'Installation réseaux Wi-Fi Mesh, routeurs 4G/5G, imprimantes & PC Windows', 'Technicien informatique à domicile. Optimisation couverture Wi-Fi villa/appartement, configuration routeurs Safaricom/Zuku, dépannage PC Windows et sauvegardes cloud.', '+254 720 444 555', '+254720444555', 'david.tech@nairobinet.co.ke', NULL, 'Interventions à domicile : Lavington, Kileleshwa, Kilimani, Westlands, Karen, Gigiri', '{"Français", "Anglais", "Swahili"}', TRUE, 5.0, 15, '{"it_tech", "lavington", "Wi-Fi", "Réseau", "Windows", "PC", "À domicile", "Safaricom", "Zuku"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-02T10:00:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Vient à domicile très ponctuel.', 'IT Tech'),
  ('it_tech_ben', 'Ben', 'it_tech', 'gigiri', 'Bilingue français anglais, +15 ans d''expérience en création de site internet vitrine et e-commerce, branding & marketing digital.', 'Bilingue français anglais, +15 ans d''expérience en création de site internet vitrine et e-commerce, branding & marketing digital.', '+254 797 810 598', '+254797810598', 'ben.tech@nairobi.pro', 'https://nairobi.pro', 'Gigiri / Runda & Remote Nairobi', '{"Français", "Anglais"}', TRUE, 5.0, 12, '{"it_tech", "gigiri", "Site Internet", "Web", "E-commerce", "Branding", "Marketing Digital", "Bilingue"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-02T10:00:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Expert web bilingue recommandé.', 'IT Tech'),
  ('loisir_road_trippin', 'ROAD TRIPPIN (Harvo OBERAI)', 'loisirs', 'westlands', 'Organisateur de Safaris, Logements, Transports & Excursions', 'Organisateur de safari, Harvo s''occupe de tout (du logement, du transport, des excursions). Je suis allée avec lui au lac Bogoria et aussi à Samburu, c''était magique !', '+254 713 254 777', '+254713254777', 'info@roadtrippin.co.ke', 'https://roadtrippin.co.ke', 'Nairobi, Kenya', '{"Français", "Anglais"}', TRUE, 5.0, 1, '{"Safari", "Excursions", "Road Trip", "Samburu", "Bogoria", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-03T10:05:00.000Z', 'Recommandé par un membre', 'Emilie T.', 5, 'Organisateur de safari, Harvo s''occupe de tout (du logement, du transport, des excursions). Je suis allée avec lui au lac Bogoria et aussi à Samburu, c''était magique !', 'Recommandation WhatsApp'),
  ('sante_2', 'Liste de notoriété médicale de l''ambassade de France', 'sante', 'lavington', 'General', 'Mis à jour régulièrement', 'Mise à jour : Mars 2025', NULL, NULL, 'https://ke.ambafrance.org/Ambassade-de-France-au-Kenya-Liste-de-notoriete-medicale-2029', 'Kenya', '{"Français", "Anglais"}', TRUE, 4.9, 18, '{"General", "Lavington", "Recommandé Communauté"}', 'Ambassade', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Mis à jour régulièrement', 'Santé'),
  ('sante_3', 'AAR Healthcare', 'sante', 'lavington', 'Ambulances', 'Voie Terrestre', '+254725225225', '+254725225225', NULL, NULL, 'Kenya', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Ambulances", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Voie Terrestre', 'Santé'),
  ('sante_4', 'EMS Ambulance', 'sante', 'lavington', 'Ambulances', 'Voie Terrestre', '+254700395395', '+254700395395', NULL, NULL, 'Kenya', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Ambulances", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Voie Terrestre', 'Santé'),
  ('sante_5', 'AMREF Flying Doctors', 'sante', 'lavington', 'Ambulances', 'Voie Aérienne', '+254-206 992 299', '+254206992299', NULL, NULL, 'Kenya', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Ambulances", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Voie Aérienne', 'Santé'),
  ('sante_6', 'Aga Khan University hospital', 'sante', 'westlands', 'Hopital', 'Aga Khan University hospital - Soins médicaux et consultations recommandés.', 'Service des urgences :', NULL, NULL, NULL, '3rd Parklands Avenue, Nairobi, Kenya', '{"Anglais", "Français"}', TRUE, 4.9, 18, '{"Hopital", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_7', 'The Nairobi Hospital', 'sante', 'lavington', 'Hopital', 'The Nairobi Hospital - Soins médicaux et consultations recommandés.', '+254703082000', '+254703082000', NULL, NULL, 'Argwings Kodhek Rd', '{"Anglais", "Français"}', TRUE, 4.9, 18, '{"Hopital", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_8', 'Dr Onkar S. Bhogal', 'sante', 'lavington', 'Generaliste', 'Dr Onkar S. Bhogal - Soins médicaux et consultations recommandés.', '+254708094208', '+254708094208', NULL, NULL, 'Park Medical Center, 6th floor, room 607', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Generaliste", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_9', 'Dr Wai Lume, médecin référent du lycée Denis Diderot de Nairobi', 'sante', 'lavington', 'Generaliste', 'Dr Wai Lume, médecin référent du lycée Denis Diderot de Nairobi - Soins médicaux et consultations recommandés.', '+254720132745', '+254720132745', NULL, NULL, 'Doctor’s Plaza. The Nairobi Hospital, Argwings Kodhek Road.', '{"Français", "Anglais"}', TRUE, 4.8, 18, '{"Generaliste", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_10', 'Dr Jacqueline Kitulu', 'sante', 'karen', 'Generaliste', 'Receptionist@KarenSurgery.com

http://karensurgery.com/index.html', '+254733642246', '+254733642246', 'Receptionist@KarenSurgery.com', 'http://karensurgery.com/index.html', 'Karen Surgery, 333 Ngong Road, juste après le rond-point du Karen Shopping Centre.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Generaliste", "Karen", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Receptionist@KarenSurgery.com

http://karensurgery.com/index.html', 'Santé'),
  ('sante_11', 'Dr Mauro Agostino Saio', 'sante', 'lavington', 'Generaliste', 'Dr Mauro Agostino Saio - Soins médicaux et consultations recommandés.', '+254 202-725-776', '+254202725776', NULL, NULL, 'Pièce 109 et 111, premier étage du Doctor’s plaza, Nairobi Hospital, Argwings Kodhek Road', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Generaliste", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_12', 'Dr Varinder Singh Sur', 'sante', 'lavington', 'Generaliste', 'Dr Varinder Singh Sur - Soins médicaux et consultations recommandés.', '+254733411334', '+254733411334', NULL, NULL, 'RDC Oriental building. Nkrumah Lane.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Generaliste", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_13', 'Dr F Alibhoy', 'sante', 'lavington', 'Generaliste', 'Dr F Alibhoy - Soins médicaux et consultations recommandés.', '+254722747966', '+254722747966', NULL, NULL, 'Aga Khan hospital, Otieno Oyoo Street.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Generaliste", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_14', 'Dr. Marie-Louise Cantamessa (généraliste avec pratique pédiatrique).', 'sante', 'karen', 'Pediatres', 'Receptionist@KarenSurgery.com

http://karensurgery.com/index.html

S’intéresse en particulier aux troubles de l’attention et aux troubles de l’alimentation', '+254733642246', '+254733642246', 'Receptionist@KarenSurgery.com', 'http://karensurgery.com/index.html', 'Karen Surgery, 333 Ngong Road, juste après le rond-point du Karen Shopping Centre.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Karen", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Receptionist@KarenSurgery.com

http://karensurgery.com/index.html

S’intéresse en particulier aux troubles de l’attention et aux troubles de l’alimentation', 'Santé'),
  ('sante_15', 'Dr. Claire Majisu', 'sante', 'lavington', 'Pediatres', 'info@lavingtonpaediatrics.com

http://lavingtonpaediatrics.com

Dr Claire a une bonne connaissance du carnet de santé français', '+254797404877', '+254797404877', 'info@lavingtonpaediatrics.com', 'http://lavingtonpaediatrics.com', 'Suite 306. Lavington Paediatrics. Chandarana building. Lavington green shopping center.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'info@lavingtonpaediatrics.com

http://lavingtonpaediatrics.com

Dr Claire a une bonne connaissance du carnet de santé français', 'Santé'),
  ('sante_16', 'Dr. Patricia Joy Mpaata', 'sante', 'lavington', 'Pediatres', 'dr.mpaataclinic@gmail.com', '+254720413003', '+254720413003', 'dr.mpaataclinic@gmail.com', NULL, 'Pièce 209. The Nairobi Hospital, Argwings Kodhek Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'dr.mpaataclinic@gmail.com', 'Santé'),
  ('sante_17', 'Dr Stephen Muhudia', 'sante', 'lavington', 'Pediatres', 'child.clinic07@yahoo.com', '+254-202-716-147', '+254202716147', 'child.clinic07@yahoo.com', NULL, 'pièce 307, 3ième étage, Doctors Plaza, Nairobi Hospital, Argwings Kodhek Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'child.clinic07@yahoo.com', 'Santé'),
  ('sante_18', 'Dr Kennedy Charles Wafula', 'sante', 'westlands', 'Pediatres', 'drwafula@yahoo.com', '+254722516690', '+254722516690', 'drwafula@yahoo.com', NULL, 'pièce 237, Doctor’s plaza, Aga Khan hospital, 3rd Parklands avenue', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'drwafula@yahoo.com', 'Santé'),
  ('sante_19', 'Dr Rachel Kariuki', 'sante', 'lavington', 'Pediatres', 'rachel.kariuki@yahoo.com', '+254725602741', '+254725602741', 'rachel.kariuki@yahoo.com', NULL, 'Social security house, 3ième étage, Nkrumah Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'rachel.kariuki@yahoo.com', 'Santé'),
  ('sante_20', 'Dr Elizabeth Kuta', 'sante', 'lavington', 'Pediatres', 'elizabethkuta@gmail.com', '+254721412262', '+254721412262', 'elizabethkuta@gmail.com', NULL, 'Aga Khan hospital, Otieno Oyoo Street.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pediatres", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'elizabethkuta@gmail.com', 'Santé'),
  ('sante_21', 'Dr Pratful S Patel', 'sante', 'westlands', 'Gynécologues Ostétriciens', 'Dr Pratful S Patel - Soins médicaux et consultations recommandés.', '+254723121516', '+254723121516', NULL, NULL, 'Pièce 114, premier étage, Doctors Plaza, Hôpital Aga Khan, third Parklands Avenue', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_22', 'Dr. S.R Patel', 'sante', 'lavington', 'Gynécologues Ostétriciens', 'srgyn@wananchi.com', '+ 254 202-720-108', '+254202720108', 'srgyn@wananchi.com', NULL, 'pièce n°5, Nairobi Hospital, Argwings Kodhek Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'srgyn@wananchi.com', 'Santé'),
  ('sante_23', 'Dr Yamal Patel', 'sante', 'westlands', 'Gynécologues Ostétriciens', 'dryamal.patel@yahoo.com', '+254728111181', '+254728111181', 'dryamal.patel@yahoo.com', NULL, 'Pièce 202, 2ième étage, Mediplaza, en face hôpital Aga Khan, 3rd parklands avenue', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'dryamal.patel@yahoo.com', 'Santé'),
  ('sante_24', 'Dr Rachel Rukaria-Kambutho', 'sante', 'westlands', 'Gynécologues Ostétriciens', 'Dr Rachel Rukaria-Kambutho - Soins médicaux et consultations recommandés.', '+254733618339', '+254733618339', NULL, NULL, 'pièce 509, cinquième étage, Doctors Plaza, Hôpital Aga Khan, third Parklands Avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_25', 'Pr Marleen Temmermann', 'sante', 'westlands', 'Gynécologues Ostétriciens', 'francophone', '+254 700 000 000', NULL, NULL, NULL, 'Doctors Plaza, Hôpital Aga Khan, third Parklands Avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'francophone', 'Santé'),
  ('sante_26', 'Dr Aruna Chudasama', 'sante', 'lavington', 'Gynécologues Ostétriciens', 'charm@africaonline.co.ke', '+254722754544', '+254722754544', 'charm@africaonline.co.ke', NULL, 'Premier étage de la clinique de consultation, hôpital de Mombasa, Off Mama Ngina Drive, next to Treasury Square.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'charm@africaonline.co.ke', 'Santé'),
  ('sante_27', 'Dr Peter Griffiths et associés 
(3 autres dentistes et un orthodontiste)', 'sante', 'westlands', 'Chirurgiens-dentistes et orthodontistes', 'info@p-griffiths.com
http://thedentalpractice.co.ke/', '+254722736439', '+254722736439', 'info@p-griffiths.com', 'http://thedentalpractice.co.ke/', 'à proximité de Waiyaki Way,Westlands.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Chirurgiens-dentistes et orthodontistes", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'info@p-griffiths.com
http://thedentalpractice.co.ke/', 'Santé'),
  ('sante_28', 'Dr Pankaj Patel', 'sante', 'lavington', 'Chirurgiens-dentistes et orthodontistes', 'ppatel@africaonline.co.ke', '+254722828611', '+254722828611', 'ppatel@africaonline.co.ke', NULL, 'The Nairobi Hospital Consulting Rooms. Hôpital de Nairobi. Argwings Kodhek Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Chirurgiens-dentistes et orthodontistes", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'ppatel@africaonline.co.ke', 'Santé'),
  ('sante_29', 'Dr Vaghela Satish', 'sante', 'lavington', 'Chirurgiens-dentistes et orthodontistes', 'Adresse-mail ; drsatishvaghela@gmail.com', '+254722411420', '+254722411420', 'drsatishvaghela@gmail.com', NULL, 'Nyali dental care, Nyali road', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Chirurgiens-dentistes et orthodontistes", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Adresse-mail ; drsatishvaghela@gmail.com', 'Santé'),
  ('sante_30', 'Dr. Hemant Saha', 'sante', 'westlands', 'Cardiologues', 'saha.hemant@gmail.com', '+254733635577', '+254733635577', 'saha.hemant@gmail.com', NULL, 'Pièce 305, 3ième étage, Doctor’s plaza, Aga Khan hospital, 3rd Parklands avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Cardiologues", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'saha.hemant@gmail.com', 'Santé'),
  ('sante_31', 'Dr. David Silverstein', 'sante', 'lavington', 'Cardiologues', 'silver@swiftkenya.com', '+254733859637', '+254733859637', 'silver@swiftkenya.com', NULL, 'Nairobi Hospital, Argwings Kodhek Road', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Cardiologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'silver@swiftkenya.com', 'Santé'),
  ('sante_32', 'Dr. Majid Warshow', 'sante', 'westlands', 'Cardiologues', 'majid.warshow@aku.edu', '+254733133224', '+254733133224', 'majid.warshow@aku.edu', NULL, '4ième étage, Doctor’s plaza, Aga Khan hospital, 3rd Parklands avenue', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Cardiologues", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'majid.warshow@aku.edu', 'Santé'),
  ('sante_33', 'Dr. Vaghela Vinesh', 'sante', 'lavington', 'Cardiologues', 'vineshvaghela@yahoo.com ; 
info@coastcardiaccentre.org', '+254720219977', '+254720219977', 'vineshvaghela@yahoo.com', NULL, 'Coast Cardiac Centre, Pandya Memorial Hospital, Dedan Kimathi Avenue', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Cardiologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'vineshvaghela@yahoo.com ; 
info@coastcardiaccentre.org', 'Santé'),
  ('sante_34', 'Dr. Muindi Wanjugu, Nairobi Chest Clinic.', 'sante', 'lavington', 'Pneumologue', 'nairobichestclinic@gmail.com

Réalise des épreuves fonctionnelles respiratoires', '+254722756272', '+254722756272', 'nairobichestclinic@gmail.com', NULL, 'Pièce 201, Doctor’s plaza, Nairobi Hospital, Argwings Kodhek Road', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pneumologue", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'nairobichestclinic@gmail.com

Réalise des épreuves fonctionnelles respiratoires', 'Santé'),
  ('sante_35', 'Dr. Saroop Singh Bansil', 'sante', 'lavington', 'Dermatologues', 'drbansil@uhmc.co.ke

www.uhmc.co.ke', '+254736476002', '+254736476002', 'drbansil@uhmc.co.ke', 'www.uhmc.co.ke', 'Pièce 4F, 4ième étage, Upper Hill medical Centre, Ralph Bunche Road, Off Valley Road', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Dermatologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'drbansil@uhmc.co.ke

www.uhmc.co.ke', 'Santé'),
  ('sante_36', 'Dr. Roop Saini', 'sante', 'lavington', 'Dermatologues', 'Dr. Roop Saini - Soins médicaux et consultations recommandés.', '+254711712512', '+254711712512', NULL, NULL, 'aile droite, 6ième étage, Mayfair Centre, Ralph Bunche Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Dermatologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_37', 'Dr. Asyago', 'sante', 'karen', 'Dermatologues', 'Dr. Asyago - Soins médicaux et consultations recommandés.', '+254712188188', '+254712188188', NULL, NULL, 'skin allergy Dermato 
Karen (à côté de The Hub)', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Dermatologues", "Karen", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_38', 'Dr Hemant Saha', 'sante', 'lavington', 'Gastro-entérologues', 'saha.hemant@gmail.com', '+254733635577', '+254733635577', 'saha.hemant@gmail.com', NULL, 'Pièce 305, 3ième étage, Doctor’s Plaza, Aga Khan Hospital', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gastro-entérologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'saha.hemant@gmail.com', 'Santé'),
  ('sante_39', 'Dr. Allan Rajula', 'sante', 'lavington', 'Gastro-entérologues', 'Dr. Allan Rajula - Soins médicaux et consultations recommandés.', '+254 203-662-000', '+254203662000', NULL, NULL, 'Aga Khan Hospital', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gastro-entérologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_40', 'Dr Devani', 'sante', 'lavington', 'Gastro-entérologues', 'Dr Devani - Soins médicaux et consultations recommandés.', '+254 700 000 000', NULL, NULL, NULL, 'Aga Khan Hospital', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gastro-entérologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_41', 'Dr. Kibata Githeko et cinq autres consultants 
(Upper Hill Eye & Laser Centre)', 'sante', 'lavington', 'Ophtalmologistes', 'office@uheal.or.ke

http://www.uheal.or.ke/', '+254714617782', '+254714617782', 'office@uheal.or.ke', 'http://www.uheal.or.ke/', '2ième étage du Upper-Hill Medical Centre, Ralph Bunche Road.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Ophtalmologistes", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'office@uheal.or.ke

http://www.uheal.or.ke/', 'Santé'),
  ('sante_42', 'Dr. D. S. Walia', 'sante', 'westlands', 'Ophtalmologistes', 'info@seeclinic.co.ke

https://seeclinic.co.ke/', '+254717783783', '+254717783783', 'info@seeclinic.co.ke', 'https://seeclinic.co.ke/', 'rez de chaussée, Mediplaza, en face hôpital Aga Khan, 3rd parklands avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Ophtalmologistes", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'info@seeclinic.co.ke

https://seeclinic.co.ke/', 'Santé'),
  ('sante_43', 'Dr. Sandhya Gokhale', 'sante', 'lavington', 'Ophtalmologistes', 'sandhya.kulkarni68@gmail.com

Specialiste Rétine', '+254736869534', '+254736869534', 'sandhya.kulkarni68@gmail.com', NULL, 'Lions eye Clinic, Aga Khan Road', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Ophtalmologistes", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'sandhya.kulkarni68@gmail.com

Specialiste Rétine', 'Santé'),
  ('sante_44', 'Dr. H. Rupani', 'sante', 'lavington', 'ORL', 'Dr. H. Rupani - Soins médicaux et consultations recommandés.', '+254-2022-727-823,', '+2542022727823,', NULL, NULL, 'hôpital de Nairobi', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"ORL", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_45', 'Dr. Asmeeta Patel', 'sante', 'westlands', 'ORL', 'draipatel.patel55@gmail.com', '+254737916838', '+254737916838', 'draipatel.patel55@gmail.com', NULL, 'pièce 228,2ième étage, Doctor’s Plaza, Aga Khan Hospital, 3rd parklands avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"ORL", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'draipatel.patel55@gmail.com', 'Santé'),
  ('sante_46', 'Dr. H. S. Jandu', 'sante', 'westlands', 'ORL', 'drharbaksh@yahoo.com', '+254733535234', '+254733535234', 'drharbaksh@yahoo.com', NULL, 'Pièce 208, 2ième étage, Mediplaza, en face hôpital Aga Khan, 3rd parklands avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"ORL", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'drharbaksh@yahoo.com', 'Santé'),
  ('sante_47', 'Dr Nelly Kitazi, psychiatre', 'sante', 'westlands', 'Psychiatres et psychologues', 'Dr Nelly Kitazi, psychiatre - Soins médicaux et consultations recommandés.', '+254724201818', '+254724201818', NULL, NULL, 'Doctors Plaza, Aga Khan Hospital, 3rd parklands avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Psychiatres et psychologues", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_48', 'Dr. H. Nabishwa, psychiatre', 'sante', 'westlands', 'Psychiatres et psychologues', 'Dr. H. Nabishwa, psychiatre - Soins médicaux et consultations recommandés.', '+254-203-662-000', '+254203662000', NULL, NULL, 'Doctors Plaza, Aga Khan Hospital, 3rd parklands avenue.', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Psychiatres et psychologues", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_49', 'Mme Lineke Sassen, psychologue clinicienne, 
francophone :', 'sante', 'westlands', 'Psychiatres et psychologues', 'linekesassen@gmail.com', '+254724842731', '+254724842731', 'linekesassen@gmail.com', NULL, 'Karen, sauf le jeudi à Westlands', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Psychiatres et psychologues", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'linekesassen@gmail.com', 'Santé'),
  ('sante_50', 'Mme Juliette Imbault, psychologue francophone', 'sante', 'lavington', 'Psychiatres et psychologues', 'j.imbault@gmail.com', '+254791010016', '+254791010016', 'j.imbault@gmail.com', NULL, '610 Mutundu Road, Old Muthaiga', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Psychiatres et psychologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'j.imbault@gmail.com', 'Santé'),
  ('sante_51', 'Mme Sophie Gidrol, psychologue francophone', 'sante', 'lavington', 'Psychiatres et psychologues', 'Spécialiste dueil / Présente sur Frencheese', 'Portable : ‪+33 6 51 15 63 32‬', NULL, NULL, NULL, 'Nairobi', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Psychiatres et psychologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Spécialiste dueil / Présente sur Frencheese', 'Santé'),
  ('sante_52', 'Petrina', 'sante', 'lavington', 'Kiné/Ostheo/Chiropracteur', 'Petrina - Soins médicaux et consultations recommandés.', '+254113056681', '+254113056681', NULL, NULL, 'Nairobi', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Kiné/Ostheo/Chiropracteur", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_53', 'Altaf', 'sante', 'lavington', 'Kiné/Ostheo/Chiropracteur', 'genou/sport rééducation', '+254724007200', '+254724007200', NULL, NULL, 'Nairobi', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Kiné/Ostheo/Chiropracteur", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'genou/sport rééducation', 'Santé'),
  ('sante_54', 'Michael Churchill', 'sante', 'kilimani', 'Kiné/Ostheo/Chiropracteur', 'https://www.chiropractic.co.ke/', '+254725463719', '+254725463719', NULL, 'https://www.chiropractic.co.ke/', 'Kandara Road, Kileleshwa', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Kiné/Ostheo/Chiropracteur", "Kilimani", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'https://www.chiropractic.co.ke/', 'Santé'),
  ('sante_55', 'Dr Thomas Corfmat / Chiro', 'sante', 'lavington', 'Kiné/Ostheo/Chiropracteur', 'https://corfmatchiro.com/
corfmatchiro@gmail.com', '+254799869967', '+254799869967', 'corfmatchiro@gmail.com', 'https://corfmatchiro.com/', 'Lavington Green Mall, Nairobi, Kenya', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Kiné/Ostheo/Chiropracteur", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'https://corfmatchiro.com/
corfmatchiro@gmail.com', 'Santé'),
  ('sante_56', 'St Austins', 'sante', 'lavington', 'Vétérinaire', 'St Austins - Soins médicaux et consultations recommandés.', '+254797795853', '+254797795853', NULL, NULL, 'Nairobi', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Vétérinaire", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_57', 'Dr Angela Muliro', 'sante', 'lavington', 'Gynécologues Ostétriciens', 'francophone', '+254702929901', '+254702929901', NULL, NULL, 'Kirichwa Rd, Nairobi, Kenya', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'francophone', 'Santé'),
  ('sante_58', 'Dr Berit', 'sante', 'lavington', 'Gynécologues Ostétriciens', 'Dr Berit - Soins médicaux et consultations recommandés.', '+254707378990', '+254707378990', NULL, NULL, 'Nairobi', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gynécologues Ostétriciens", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_59', 'Dr. Adil Waris, Aga Khan', 'sante', 'westlands', 'Pneumologue', 'Pediatre pneumologue', '25 42 03 66 27 02', NULL, NULL, NULL, 'Pièce 403, Doctor’s plaza, Aga Khan hospital, 3rd Parklands avenue', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Pneumologue", "Westlands", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Pediatre pneumologue', 'Santé'),
  ('sante_60', 'Dr. Reena Shah', 'sante', 'lavington', 'Gastro-entérologues', 'consultant physician, 
section head of infectious diseases', '+254203662117', '+254203662117', NULL, NULL, 'Aga Khan', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gastro-entérologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'consultant physician, 
section head of infectious diseases', 'Santé'),
  ('sante_61', 'Dr. Henry', 'sante', 'lavington', 'Gastro-entérologues', 'Dr. Henry - Soins médicaux et consultations recommandés.', '+254 700 000 000', NULL, NULL, NULL, 'Upperhill, Fortis Suites 5th Floor', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gastro-entérologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_62', 'Dr. Thomas MBWELE MUTIE', 'sante', 'lavington', 'Gastro-entérologues', 'Dr. Thomas MBWELE MUTIE - Soins médicaux et consultations recommandés.', '+254717967285', '+254717967285', NULL, NULL, 'Nairobi Hospital Plaza, ground floor', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Gastro-entérologues", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_63', 'Dr Fabian Collis', 'sante', 'lavington', 'Podologue', 'Dr Fabian Collis - Soins médicaux et consultations recommandés.', '+254720018377', '+254720018377', NULL, NULL, 'Lower Kabete Rd', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Podologue", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('sante_64', 'Dr Naji Abdullah Naji Said', 'sante', 'lavington', 'Urologue', 'Dr Naji Abdullah Naji Said - Soins médicaux et consultations recommandés.', '+254203754015', '+254203754015', NULL, NULL, 'Address: 3rd Floor Suite 334 Aga Khan University Hospital Doctors Plaza', '{"Anglais", "Français"}', TRUE, 4.8, 18, '{"Urologue", "Lavington", "Recommandé Communauté"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Santé'),
  ('taxi_3', 'Absolute Michael', 'loisirs', 'lavington', 'Chauffeur Privé / Safari Guide', 'Grosse voiture', '+254733901183', '+254733901183', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Grosse voiture (Tarif: )', 'TaxiSafaris'),
  ('taxi_4', 'Peter', 'transports', 'lavington', 'Driver/Guide/Car', 'Peter is really awsome everyone I recommended him to, really liked him. Hes is a great guide, always finding the hidden spots and willing to go (a bit) off tracks when possible. Hes has two brothers one is very good too, the other one not so much. Classic Safari Van 10 seaters.', '+254724377898', '+254724377898', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Peter is really awsome everyone I recommended him to, really liked him. Hes is a great guide, always finding the hidden spots and willing to go (a bit) off tracks when possible. Hes has two brothers one is very good too, the other one not so much. Classic Safari Van 10 seaters. (Tarif: Around 19,000 KES per day (a bit less if many days) for the car (safari Van), fuel, driver/guide, park entries (driver+car), etc.))', 'TaxiSafaris'),
  ('taxi_5', 'Ben Mathenge - Game Africa Safaris', 'transports', 'lavington', 'Chauffeur/Guide', 'Nairobi National Park', '+254723370677', '+254723370677', NULL, 'www.gameafricasafaris.com', NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Nairobi National Park (Tarif: )', 'TaxiSafaris'),
  ('taxi_6', 'Sammy', 'transports', 'lavington', 'Driver/Guide/Car', 'Fiable, gentil, ponctuel, dispo a Nairobi et pour de longs voyages', '+254727875006', '+254727875006', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Fiable, gentil, ponctuel, dispo a Nairobi et pour de longs voyages (Tarif: )', 'TaxiSafaris'),
  ('taxi_7', 'Hunter', 'loisirs', 'lavington', 'Chauffeur Privé / Safari Guide', 'has the best local guides and supports local community,his prices are so friendly woudl always recommend  and has 15 landcruisers Pays attention to detail for all age groups', '+254739149798', '+254739149798', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'has the best local guides and supports local community,his prices are so friendly woudl always recommend  and has 15 landcruisers Pays attention to detail for all age groups (Tarif: 14000 onwards  depends on the location for the car (safari CAR), fuel, driver/guide, park entries (driver+car), etc.))', 'TaxiSafaris'),
  ('taxi_8', 'Samuel Chacal  - Expedition', 'loisirs', 'lavington', 'Chauffeur Privé / Safari Guide', 'Frères ayant appris le français à l''alliance fr Mombasa', '+254728625348', '+254728625348', NULL, NULL, NULL, '{"Français", "Anglais"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Frères ayant appris le français à l''alliance fr Mombasa (Tarif: )', 'TaxiSafaris'),
  ('taxi_9', 'The Sacred Wilderness', 'loisirs', 'lavington', 'Présent sur frenchesse', 'Service de transport et excursions safari.', '+254739149798', '+254739149798', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '(Tarif: thesacredwilderness.org)', 'TaxiSafaris'),
  ('taxi_10', 'Antonio', 'loisirs', 'lavington', 'Guide Tsavo', 'Service de transport et excursions safari.', '+254724330799', '+254724330799', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '(Tarif: )', 'TaxiSafaris'),
  ('taxi_11', 'David', 'transports', 'lavington', 'Guide/Driver', 'National Park', '+254733282110', '+254733282110', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'National Park (Tarif: )', 'TaxiSafaris'),
  ('taxi_12', 'Paul Mwangi', 'loisirs', 'lavington', 'Car Rent', 'Service de transport et excursions safari.', '+254722540760', '+254722540760', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '(Tarif: )', 'TaxiSafaris'),
  ('taxi_13', 'Maina Kabithi', 'transports', 'lavington', 'Chauffeur/Guide', 'Groupe de chauffeurs fiables', '+254722780502', '+254722780502', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.9, 24, '{"Chauffeur", "Safari", "Recommandé"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Groupe de chauffeurs fiables (Tarif: )', 'TaxiSafaris'),
  ('fundi_3', 'Simon - Plombier', 'fundis', 'lavington', 'Artisan Plombier', 'Artisan qualifié (Plombier) recommandé pour interventions à domicile.', '+254725639837', '+254725639837', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Plombier", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_4', 'Bildad Simiyu - Plombier', 'fundis', 'lavington', 'Artisan Plombier', 'Artisan qualifié (Plombier) recommandé pour interventions à domicile.', '+254708011173', '+254708011173', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Plombier", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_5', 'Oscar - Plombier', 'fundis', 'lavington', 'Artisan Plombier', 'Artisan qualifié (Plombier) recommandé pour interventions à domicile.', '+254710808758', '+254710808758', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Plombier", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_6', 'James - Plombier', 'fundis', 'lavington', 'Artisan Plombier', 'Artisan qualifié (Plombier) recommandé pour interventions à domicile.', '+254723101258', '+254723101258', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Plombier", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_7', 'Alex Wachira - Electricien', 'fundis', 'lavington', 'Artisan Electricien', 'Artisan qualifié (Electricien) recommandé pour interventions à domicile.', '+254722711304', '+254722711304', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Electricien", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_8', 'Christine - Couture', 'fundis', 'lavington', 'Artisan Couture', 'Good work, quite cheap. Curtains, pillows, etc.', '+254713538149', '+254713538149', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Couture", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Good work, quite cheap. Curtains, pillows, etc.', 'Fundi Reco'),
  ('fundi_9', 'Vithal - Couture', 'fundis', 'lavington', 'Artisan Couture', 'Artisan qualifié (Couture) recommandé pour interventions à domicile.', '+254736873339', '+254736873339', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Couture", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_10', 'Jane Wanjiku (Seamstress) - Couture', 'fundis', 'lavington', 'Artisan Couture', 'Elle est super!', '+254721476033', '+254721476033', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Couture", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Elle est super!', 'Fundi Reco'),
  ('fundi_11', 'Beatrice - Couture', 'fundis', 'lavington', 'Artisan Couture', 'Artisan qualifié (Couture) recommandé pour interventions à domicile.', '+254720258120', '+254720258120', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Couture", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_12', 'Auma - Couture', 'fundis', 'lavington', 'Artisan Couture', 'Artisan qualifié (Couture) recommandé pour interventions à domicile.', '+254737449589', '+254737449589', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Couture", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_14', 'Boucherie en ligne / Flavie - Marché / Epicerie', 'fundis', 'lavington', 'Artisan Marché / Epicerie', 'https://www.toromeat.com/ Livraison à domicile', '+254724110695', '+254724110695', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Marché / Epicerie", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'https://www.toromeat.com/ Livraison à domicile', 'Fundi Reco'),
  ('fundi_15', 'Kenavo Production / Jean-Claude - Marché / Epicerie', 'fundis', 'lavington', 'Artisan Marché / Epicerie', 'Paté, fromage, etc', '+254729515941', '+254729515941', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Marché / Epicerie", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Paté, fromage, etc', 'Fundi Reco'),
  ('fundi_16', 'George Otieno - Demenagement', 'fundis', 'lavington', 'Artisan Demenagement', 'Camion pour déménagement', '+254723551941', '+254723551941', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Demenagement", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Camion pour déménagement', 'Fundi Reco'),
  ('fundi_17', 'Nellions - Demenagement', 'fundis', 'lavington', 'Artisan Demenagement', 'Mise à dispo de cartons', '+254700000002', '+254700000002', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Demenagement", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Mise à dispo de cartons', 'Fundi Reco'),
  ('fundi_18', 'Alfred Alpha - Demenagement', 'fundis', 'lavington', 'Artisan Demenagement', 'Artisan qualifié (Demenagement) recommandé pour interventions à domicile.', '+254722102902', '+254722102902', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Demenagement", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_19', 'Capital Moving - Demenagement', 'fundis', 'lavington', 'Artisan Demenagement', 'Permet également de stocker meubles', '+254722454315', '+254722454315', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Demenagement", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Permet également de stocker meubles', 'Fundi Reco'),
  ('fundi_20', 'Chris - Peintre', 'fundis', 'lavington', 'Artisan Peintre', 'Artisan qualifié (Peintre) recommandé pour interventions à domicile.', '+254726518019', '+254726518019', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Peintre", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_21', 'Duncan - Peintre', 'fundis', 'lavington', 'Artisan Peintre', 'Artisan qualifié (Peintre) recommandé pour interventions à domicile.', '+254727131868', '+254727131868', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Peintre", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_22', 'Josephat - Peintre', 'fundis', 'lavington', 'Artisan Peintre', 'Artisan qualifié (Peintre) recommandé pour interventions à domicile.', '+254726008880', '+254726008880', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Peintre", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_23', 'Samy - Peintre', 'fundis', 'lavington', 'Artisan Peintre', 'Artisan qualifié (Peintre) recommandé pour interventions à domicile.', '+254720938485', '+254720938485', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Peintre", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_24', 'Daniel - Peintre', 'fundis', 'lavington', 'Artisan Peintre', 'Artisan qualifié (Peintre) recommandé pour interventions à domicile.', '+254710773160', '+254710773160', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Peintre", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_25', 'Crumbs (pate à pizza livraison) - Marché / Epicerie', 'fundis', 'lavington', 'Artisan Marché / Epicerie', 'livraison à domicile', '+254759200487', '+254759200487', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Marché / Epicerie", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'livraison à domicile', 'Fundi Reco'),
  ('fundi_26', 'Computer Mart - Réparation écran', 'fundis', 'lavington', 'Artisan Réparation écran', 'Mac', '+254724588876', '+254724588876', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Réparation écran", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Mac', 'Fundi Reco'),
  ('fundi_27', 'Your Apps Lency - Réparation écran', 'fundis', 'lavington', 'Artisan Réparation écran', 'Réparation écran externe', '+254780688637', '+254780688637', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Réparation écran", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Réparation écran externe', 'Fundi Reco'),
  ('fundi_28', 'Krishna plaza- 3rd Parklands - Marché / Epicerie', 'fundis', 'lavington', 'Artisan Marché / Epicerie', 'Vente d''épices', '+254 700 000 000', NULL, NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Marché / Epicerie", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Vente d''épices', 'Fundi Reco'),
  ('fundi_29', 'Haroun - Musique', 'fundis', 'lavington', 'Artisan Musique', 'Prof piano à domicile', '+254796452350', '+254796452350', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Musique", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Prof piano à domicile', 'Fundi Reco'),
  ('fundi_30', 'Mylana / Laini rolls - Marché / Epicerie', 'fundis', 'lavington', 'Artisan Marché / Epicerie', 'Rouleau de printemps', '+32 475455500', '+32475455500', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Marché / Epicerie", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Rouleau de printemps', 'Fundi Reco'),
  ('fundi_31', 'Romain - Tatoueur', 'fundis', 'lavington', 'Artisan Tatoueur', 'Artisan qualifié (Tatoueur) recommandé pour interventions à domicile.', '+254799402552', '+254799402552', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Tatoueur", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Fundi Reco'),
  ('fundi_32', 'Shawn Kay Davies - Tatoueur', 'fundis', 'lavington', 'Artisan Tatoueur', 'Sur Rdv uniquement', '+254714413329', '+254714413329', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Tatoueur", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Sur Rdv uniquement', 'Fundi Reco'),
  ('fundi_33', 'Gobeba - Marché / Epicerie', 'fundis', 'lavington', 'Artisan Marché / Epicerie', 'Livraison Eau', '+254710440403', '+254710440403', NULL, NULL, NULL, '{"Anglais", "Swahili"}', TRUE, 4.8, 16, '{"Marché / Epicerie", "Fundi", "Maison", "Dépannage"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Livraison Eau', 'Fundi Reco'),
  ('soins_3', 'Salon malibu', 'autres', 'gigiri', 'Coiffeur', 'Prestations Coiffeur recommandées par la communauté.', '+254 700 000 000', NULL, NULL, NULL, 'Village market', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Gigiri"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_4', 'A great Idea Salon', 'autres', 'lavington', 'Coiffeur', 'Prestations Coiffeur recommandées par la communauté.', '+254 707 96306', '+25470796306', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_5', 'Abi / Kami', 'autres', 'lavington', 'Coiffeur', 'Prestations Coiffeur recommandées par la communauté.', '+254711216030', '+254711216030', NULL, NULL, 'Riverside drive', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_6', 'Tirath', 'autres', 'lavington', 'Coiffeur', 'Prestations Coiffeur recommandées par la communauté.', '+254707812900', '+254707812900', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_7', 'Nothing Like It', 'autres', 'karen', 'Coiffeur', 'Coiffeur / esthéticienne / Massage / Laser / Onglerie', '+254 700 000 000', NULL, NULL, NULL, 'Karen', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Coiffeur / esthéticienne / Massage / Laser / Onglerie', 'MassageSoinsYogaactivités sport'),
  ('soins_8', 'Mary Nasambu', 'autres', 'lavington', 'Massage', 'Massage lympatiques', '+254719843400', '+254719843400', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage lympatiques', 'MassageSoinsYogaactivités sport'),
  ('soins_9', 'Grace', 'autres', 'lavington', 'Massage', 'Massage lympatiques', '+254725410181', '+254725410181', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage lympatiques', 'MassageSoinsYogaactivités sport'),
  ('soins_10', 'Fatuma', 'autres', 'lavington', 'Massage', 'Massage à domicile
Reflexology', '+254721556633', '+254721556633', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage à domicile
Reflexology', 'MassageSoinsYogaactivités sport'),
  ('soins_11', 'Lucy', 'autres', 'lavington', 'Massage', 'Massage à domicile', '+254721990596', '+254721990596', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage à domicile', 'MassageSoinsYogaactivités sport'),
  ('soins_12', 'Serenity Spa', 'autres', 'gigiri', 'Massage/Spa', 'Prestations Massage/Spa recommandées par la communauté.', '+254 700 000 000', NULL, NULL, 'https://www.serenityspa.co.ke/', 'Gigiri/Karen/Kitisuru', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage/Spa", "Bien-être", "Soins", "Gigiri"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_13', 'Viviane', 'autres', 'lavington', 'Massage', 'Massage à domicile - tonique et doux, de vraies mains de fées, réflexo aussi', '+254741129765', '+254741129765', NULL, NULL, 'À domicile', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage à domicile - tonique et doux, de vraies mains de fées, réflexo aussi', 'MassageSoinsYogaactivités sport'),
  ('soins_14', 'Loise', 'autres', 'lavington', 'Massage', 'Massage à domicile', '+254739510306', '+254739510306', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage à domicile', 'MassageSoinsYogaactivités sport'),
  ('soins_15', 'Hamisi Mwapesa', 'autres', 'lavington', 'Massage', 'Massage à domicile
Deep tissue spécialité', '+254716599728', '+254716599728', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage à domicile
Deep tissue spécialité', 'MassageSoinsYogaactivités sport'),
  ('soins_16', 'Rose', 'autres', 'lavington', 'Massage', 'Massage à domicile', '+254720414456', '+254720414456', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Massage", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Massage à domicile', 'MassageSoinsYogaactivités sport'),
  ('soins_17', 'Amanda', 'sport', 'lavington', 'Yoga', 'Amanda''s yoga class emphasizes technique through a unique combination of flow, strength and mobility movements', '+254792650930', '+254792650930', NULL, NULL, 'Cours différents endroits à Nairobi', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Yoga", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Amanda''s yoga class emphasizes technique through a unique combination of flow, strength and mobility movements', 'MassageSoinsYogaactivités sport'),
  ('soins_18', 'Kanga Studio', 'sport', 'lavington', 'Yoga', 'Cours de Nancy recommandés', '+254759956291', '+254759956291', NULL, NULL, 'Online
Peponi Road', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Yoga", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Cours de Nancy recommandés', 'MassageSoinsYogaactivités sport'),
  ('soins_19', 'Liz Salima', 'sport', 'lavington', 'Yoga', 'Prestations Yoga recommandées par la communauté.', '+254775406236', '+254775406236', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Yoga", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_20', 'Moses (barber)', 'autres', 'lavington', 'Coiffeur', 'Barber', '+254723563694', '+254723563694', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Barber', 'MassageSoinsYogaactivités sport'),
  ('soins_21', 'Adham Ali Theias Beauty', 'autres', 'lavington', 'Coiffeur', 'Barber', '+254745359165', '+254745359165', NULL, NULL, '', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Barber', 'MassageSoinsYogaactivités sport'),
  ('soins_22', 'Milla Otieno', 'sport', 'lavington', 'Sport', 'Excellent coach de musculation et fitness, proposant des programmes efficaces où l’on constate de vrais progrès, avec une personnalité motivante et agréable', '+254712782638', '+254712782638', NULL, NULL, 'A domicile', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Sport", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Excellent coach de musculation et fitness, proposant des programmes efficaces où l’on constate de vrais progrès, avec une personnalité motivante et agréable', 'MassageSoinsYogaactivités sport'),
  ('soins_23', 'Jiu Jitsu Academy', 'sport', 'lavington', 'Sport', 'Programme aussi pour les enfants', '+254798566294', '+254798566294', NULL, NULL, '3rd floor New Muthaiga 
Shopping Mall Thigiri Rd', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Sport", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Programme aussi pour les enfants', 'MassageSoinsYogaactivités sport'),
  ('soins_24', 'The Colosseum 
Fitness Centre
Box Thai', 'sport', 'lavington', 'Sport', 'Prestations Sport recommandées par la communauté.', '+254 700 000 000', NULL, NULL, NULL, 'Adams Arcade', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Sport", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_25', 'Forward Equestrian Centre', 'sport', 'lavington', 'Sport', 'Ecole d''équitation, compétition, pension-travail.
Pony camp et ballade dans la Karura possible', '+254769126714', '+254769126714', NULL, 'https://www.instagram.com/forward.equestrian.centre/', '4,1H Tate Close, KItisuru', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Sport", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Ecole d''équitation, compétition, pension-travail.
Pony camp et ballade dans la Karura possible', 'MassageSoinsYogaactivités sport'),
  ('soins_26', 'Horse Association of Kenya', 'sport', 'karen', 'Sport', 'Association qui s''occupe de toute la vie equestre du kenya, en lien avec le dressage, saut d''obstacle, concours complet, Organisation de compétition, stage, formation etc,
Liste des écoles d''équitation : https://www.horseassociationofkenya.com/riding-school-instructors', '+254724804564', '+254724804564', NULL, 'https://www.horseassociationofkenya.com/', 'HAK Office Ngong Racecourse - Nairobi 
Off Ngong Road
PO BOX 24555 Karen 00502 Nairobi', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Sport", "Bien-être", "Soins", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Association qui s''occupe de toute la vie equestre du kenya, en lien avec le dressage, saut d''obstacle, concours complet, Organisation de compétition, stage, formation etc,
Liste des écoles d''équitation : https://www.horseassociationofkenya.com/riding-school-instructors', 'MassageSoinsYogaactivités sport'),
  ('soins_27', 'Tom / Hairffice', 'autres', 'gigiri', 'Coiffeur', 'Prestations Coiffeur recommandées par la communauté.', '+254731022220', '+254731022220', NULL, NULL, 'Limuru rd', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Coiffeur", "Bien-être", "Soins", "Gigiri"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'MassageSoinsYogaactivités sport'),
  ('soins_28', 'Philomena N''Dungu', 'autres', 'lavington', 'Pedicure/manicure', 'Tres bonne manicure/pedicure a domicile.', '+254722330776', '+254722330776', NULL, NULL, 'A domicile', '{"Anglais", "Swahili"}', TRUE, 4.8, 12, '{"Pedicure/manicure", "Bien-être", "Soins", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Tres bonne manicure/pedicure a domicile.', 'MassageSoinsYogaactivités sport'),
  ('sortir_3', 'Nairobi Accueil', 'loisirs', 'lavington', 'All', 'Bonne adresse All à Lavington.', '+254 700 000 000', NULL, NULL, 'https://nairobi-accueil.org/association/', 'All', '{"Anglais"}', TRUE, 4.9, 35, '{"All", "Gastronomie", "Sortir", "Lavington"}', 'Nairobi Accueil', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_4', 'Céline & Lolo', 'loisirs', 'lavington', 'Restaurant / Café', 'Deco française année 60 / bistro français. Si vous êtes en manque d''oeufs mayo, saucisson : alors foncez!', '+254117070707', '+254117070707', NULL, 'www.celineandlolo.com/bistro-lolo', 'Kabarsiran Ave, Lavington', '{"Français", "Anglais"}', TRUE, 4.9, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Deco française année 60 / bistro français. Si vous êtes en manque d''oeufs mayo, saucisson : alors foncez!', 'Sortir à Nairobi'),
  ('sortir_5', 'Mambo Italia', 'loisirs', 'lavington', 'Restaurant / Café', 'Rooftop mall
Pizza
Jeux pour enfants
(Existe différentes branches dans Nairobi)', '+254 700 000 000', NULL, NULL, 'https://share.google/05xUwKEcItNSNU7HU', 'Located on the 2nd floor of Lavington Curve, at the junction of James Gichuru Rd and Naushad Merali Drive.', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Rooftop mall
Pizza
Jeux pour enfants
(Existe différentes branches dans Nairobi)', 'Sortir à Nairobi'),
  ('sortir_6', 'Chekafe', 'loisirs', 'kilimani', 'Restaurant / Café', 'Restaurant Japonais, excellent Ramen
En profiter pour découvrir Cheche Bookshop, librairie indé qui propose à la vente de nombreux auteurs du continent', '+254717700666', '+254717700666', NULL, 'https://www.instagram.com/chekafe/', 'Nouvelle adresse
Riara road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Kilimani"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Restaurant Japonais, excellent Ramen
En profiter pour découvrir Cheche Bookshop, librairie indé qui propose à la vente de nombreux auteurs du continent', 'Sortir à Nairobi'),
  ('sortir_7', 'Under the Radar', 'loisirs', 'kilimani', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Kilimani.', '+254 700 000 000', NULL, NULL, NULL, 'KILIMANI', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Kilimani"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_8', 'Geco Café', 'loisirs', 'lavington', 'Restaurant / Café', 'Lieu pour sortir
Concerts', '+254 700 000 000', NULL, NULL, 'https://share.google/7Iax1nBtbfShWpMKm', 'Mbaazi avenue, Lavington', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Lieu pour sortir
Concerts', 'Sortir à Nairobi'),
  ('sortir_9', 'The Wine Bar', 'loisirs', 'lavington', 'Restaurant / Café', 'Tapas
Verre de vin', '+254 700 000 000', NULL, NULL, 'https://thewinebox.biz/the-wine-bar/', 'Lavington Corner Mall along James Gichuru Road,
opposite Rubis Petrol Station', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Tapas
Verre de vin', 'Sortir à Nairobi'),
  ('sortir_10', 'Kengeles', 'loisirs', 'lavington', 'Restaurant / Café', 'Pub
Diffuse sport à la TV', '+254 700 000 000', NULL, NULL, 'https://tamarind.co.ke/kengeles/', 'Lavington mall', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Pub
Diffuse sport à la TV', 'Sortir à Nairobi'),
  ('sortir_11', 'Bamba', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Lavington.', '+254 700 000 000', NULL, NULL, 'https://www.bamba-restaurant-kenya.com/', '847 Amboseli Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_12', 'Kalamata', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Lavington.', '+254 700 000 000', NULL, NULL, 'https://share.google/jC10iY82kK3sp94DX', 'along James Gichuru Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_13', 'Crafty Chameleon', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonnes bières, four à pizza', '+254 700 000 000', NULL, NULL, 'https://craftychameleon.co.ke/', 'along James Gichuru Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Bonnes bières, four à pizza', 'Sortir à Nairobi'),
  ('sortir_14', 'Habesha', 'loisirs', 'lavington', 'Restaurant / Café', 'Excellent restaurant ethiopien', '+254733730469', '+254733730469', NULL, 'www.habesharestaurant.co.ke', 'Argwings Kodhek Rd, Lavington', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Excellent restaurant ethiopien', 'Sortir à Nairobi'),
  ('sortir_15', 'La Salumeria', 'loisirs', 'lavington', 'Restaurant / Café', 'Restaurant italien, deco un peu rustique
Je conseille les gnocchi maisons!', '+254722530288', '+254722530288', NULL, NULL, 'Dhajay Apartments, Valley Arcade, Lavington', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Restaurant italien, deco un peu rustique
Je conseille les gnocchi maisons!', 'Sortir à Nairobi'),
  ('sortir_16', 'Misono', 'loisirs', 'kilimani', 'Restaurant / Café', 'Un des plus anciens japonais de Nairobi', '+254722511229', '+254722511229', NULL, NULL, 'Adams Arcade, The Greenhouse, Ngong Rd', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Kilimani"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Un des plus anciens japonais de Nairobi', 'Sortir à Nairobi'),
  ('sortir_17', 'Cedars', 'loisirs', 'kilimani', 'Restaurant / Café', 'Cedars propose une cuisine libanaise à des prix très abordables. Traditionnel mezzé jusqu’à 24 plats. Jardin', '+254722512916', '+254722512916', NULL, 'https://www.cedarsnairobi.com/', 'Lenana Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Kilimani"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Cedars propose une cuisine libanaise à des prix très abordables. Traditionnel mezzé jusqu’à 24 plats. Jardin', 'Sortir à Nairobi'),
  ('sortir_18', 'Shokudo', 'loisirs', 'kilimani', 'Restaurant / Café', 'Japonais', '+254759555501', '+254759555501', NULL, 'https://share.google/fjshfjnXUfKV0GM8F', 'Lenana road,Astrol Petrol station', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Kilimani"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Japonais', 'Sortir à Nairobi'),
  ('sortir_19', 'Pickled', 'loisirs', 'lavington', 'Restaurant / Café', 'Pour manger sur le pouce, excellents sandwishes', '+254114521531', '+254114521531', NULL, NULL, '1269 Olenguruone Ave, Lavington', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Pour manger sur le pouce, excellents sandwishes', 'Sortir à Nairobi'),
  ('sortir_20', 'Amani Ya Juu', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254 700 000 000', NULL, NULL, NULL, 'Westlands', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_21', 'Amani Gardens', 'loisirs', 'westlands', 'Restaurant / Café', 'Jeux pour enfants', '+254 700 000 000', NULL, NULL, NULL, 'Westlands', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Jeux pour enfants', 'Sortir à Nairobi'),
  ('sortir_22', 'About thyme', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254721850026', '+254721850026', NULL, 'www.about-thyme.com', 'Eldama Ravine Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_23', 'Até', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254700283283', '+254700283283', NULL, 'www.ate.co.ke', '220 Kyuna Crescent', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_24', 'Beit é selam', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254702882508', '+254702882508', NULL, 'www.instagram.com/beiteselam', 'Maua Close, off Parklands Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_25', 'Dijo', 'loisirs', 'westlands', 'Restaurant / Café', 'Restaurant français', '+254726345512', '+254726345512', NULL, 'www.instagram.com/dijo.nairobi', 'The Mandrake, Ring Rd Parklands', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Restaurant français', 'Sortir à Nairobi'),
  ('sortir_26', 'Furusato', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254722488706', '+254722488706', NULL, NULL, 'Ring Rd Parklands', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_27', 'Mythos Taverna', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254115312209', '+254115312209', NULL, 'www.mythos-restaurant.com', 'Mwanzi Market Mwanzi Rd', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_28', 'Open House', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254727726345', '+254727726345', NULL, 'www.openhouserestaurant.co.ke', 'Gallant mall, Parklands Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_29', 'Peponi''s', 'loisirs', 'westlands', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Westlands.', '+254715717171', '+254715717171', NULL, NULL, 'Peponi Rd', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_30', 'Tin Roof Cafe', 'loisirs', 'karen', 'Restaurant / Café', 'Jeux pour enfants', '+254748259066', '+254748259066', NULL, 'www.tinroof.cafe', 'in front of Karen the Hub 70 Dagoretti Road, House of Treasures, Karen', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Jeux pour enfants', 'Sortir à Nairobi'),
  ('sortir_31', 'Cultiva Farm', 'loisirs', 'karen', 'Restaurant / Café', 'Ouvert du mercredi au Dimanche
Concept « de la ferme à l’assiette », mettant à l’honneur des ingrédients locaux et biologiques.', '+254701579902', '+254701579902', NULL, 'www.cultivakenya.com', 'Pofu Road, Karen', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Ouvert du mercredi au Dimanche
Concept « de la ferme à l’assiette », mettant à l’honneur des ingrédients locaux et biologiques.', 'Sortir à Nairobi'),
  ('sortir_32', 'Asmara', 'loisirs', 'karen', 'Restaurant / Café', 'Jeux pour enfants', '+254 700 000 000', NULL, NULL, NULL, 'KAREN', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Jeux pour enfants', 'Sortir à Nairobi'),
  ('sortir_33', 'Talisman', 'loisirs', 'karen', 'Restaurant / Café', 'Jeux pour enfants', '+254705999997', '+254705999997', NULL, 'www.thetalismanrestaurant.com', '320 Ngong Road, Karen, Nairobi', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Jeux pour enfants', 'Sortir à Nairobi'),
  ('sortir_34', 'Under the Swahili tree', 'loisirs', 'karen', 'Restaurant / Café', 'weekends they have kids pizza making, face painting bouncing castle', '+254 700 000 000', NULL, NULL, NULL, 'KAREN', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'weekends they have kids pizza making, face painting bouncing castle', 'Sortir à Nairobi'),
  ('sortir_35', 'Big Smoke', 'loisirs', 'karen', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Karen.', '+254 700 000 000', NULL, NULL, NULL, 'KAREN', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_36', 'Cave à manger', 'loisirs', 'karen', 'Restaurant / Café', 'Un espace chaleureux et intimiste où les meilleurs vins ont déjà été sélectionnés pour vous. Des sommeliers ont associé chaque plat à deux vins, proposés à gauche et à droite du menu, pour faciliter votre choix et sublimer l’expérience gastronomique.', '+254748428655', '+254748428655', NULL, 'www.thewinebox.biz/cave-a-manger', 'Karen Plains Rd, opposite Waterfront Mall', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Un espace chaleureux et intimiste où les meilleurs vins ont déjà été sélectionnés pour vous. Des sommeliers ont associé chaque plat à deux vins, proposés à gauche et à droite du menu, pour faciliter votre choix et sublimer l’expérience gastronomique.', 'Sortir à Nairobi'),
  ('sortir_37', 'Matteo''s', 'loisirs', 'karen', 'Restaurant / Café', 'Ce restaurant italien familial sert des pizzas artisanales et des plats traditionnels italiens dans un cadre de jardin tropical luxuriant. Une véritable escapade gourmande aux saveurs de l’Italie, au cœur de Karen. Une adresse très appréciée des habitants du quartier.', '+254110098333', '+254110098333', NULL, NULL, 'Ngong Road and Karen Road junction', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Ce restaurant italien familial sert des pizzas artisanales et des plats traditionnels italiens dans un cadre de jardin tropical luxuriant. Une véritable escapade gourmande aux saveurs de l’Italie, au cœur de Karen. Une adresse très appréciée des habitants du quartier.', 'Sortir à Nairobi'),
  ('sortir_38', 'Haru', 'loisirs', 'karen', 'Restaurant / Café', 'Pour les amaterus de sushis', '+254720945400', '+254720945400', NULL, NULL, 'Karen Professional Centre, Karen Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Pour les amaterus de sushis', 'Sortir à Nairobi'),
  ('sortir_39', 'Mam Mam', 'loisirs', 'karen', 'Restaurant / Café', '2e branch du restaurant / excellente nourriture vietnamienne', '+254790335350', '+254790335350', NULL, 'https://www.instagram.com/mammam.ke', 'Mytown Mall Karen', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '2e branch du restaurant / excellente nourriture vietnamienne', 'Sortir à Nairobi'),
  ('sortir_40', 'Karen Blixen Coffee 
Garden', 'loisirs', 'karen', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Karen.', '+254 700 000 000', NULL, NULL, 'https://www.karenblixencoffeegardens.com/dining/', 'KAREN', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_41', 'The Saddle & Boot', 'loisirs', 'karen', 'Restaurant / Café', 'Un gastropub à l’énergie londonienne et à l’âme nairobienne. L’endroit idéal pour un déjeuner décontracté, un dîner animé ou une soirée entre amis.', '+254707061123', '+254707061123', NULL, 'www.instagram.com/saddleandboot/', 'Ngong Racecourse, off Ngong Rd', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Karen"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Un gastropub à l’énergie londonienne et à l’âme nairobienne. L’endroit idéal pour un déjeuner décontracté, un dîner animé ou une soirée entre amis.', 'Sortir à Nairobi'),
  ('sortir_42', '⁠The Shamba Cafe', 'loisirs', 'lavington', 'Restaurant / Café', 'Grand jardin, activités pour enfants
Vente fruits/legumes bio
Bacs pour recyclage', '+254 700 000 000', NULL, NULL, NULL, 'LORESHO', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Grand jardin, activités pour enfants
Vente fruits/legumes bio
Bacs pour recyclage', 'Sortir à Nairobi'),
  ('sortir_43', 'Wasp & Sprout', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Lavington.', '+254799873422', '+254799873422', NULL, 'https://share.google/fU3KUpOnJukQ8VUef', 'Loresho Shopping Centre, Loresho Ridge Road.', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_44', 'Karura Forest', 'loisirs', 'lavington', 'Activity / Walk / Nature', 'https://chng.it/6C89248Zzt

Pétition suite à la reprise de la foret par KFS', '+254 700 000 000', NULL, NULL, 'https://chng.it/6C89248Zzt', 'Karura Forest', '{"Anglais"}', TRUE, 4.8, 35, '{"Activity / Walk / Nature", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'https://chng.it/6C89248Zzt

Pétition suite à la reprise de la foret par KFS', 'Sortir à Nairobi'),
  ('sortir_45', 'The River Cafe', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Lavington.', '+254725969891', '+254725969891', NULL, 'https://www.therivercafekenya.com/', 'Inside Karura Forest,
 Off Limuru road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_46', 'Sigiria Coffee House', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Lavington.', '+254 700 000 000', NULL, NULL, NULL, 'https://maps.google.com/maps?hl=fr&gl=fr&um=1&ie=UTF-8&fb=1&sa=X&ftid=0x182f17907d7231db:0xd23d7a91b9856e7b', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_47', 'Grenier à Pain', 'loisirs', 'lavington', 'Restaurant / Café', 'Bonne adresse Restaurant / Café à Lavington.', '+254799848118', '+254799848118', NULL, 'https://www.legrenierapain.co.ke/', 'Branche principale : 9 Riverside Building,
Ground Floor

Présent aussi au Yaya center, Warwick et Mwanzi Market', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_48', 'Two Grapes The Winery', 'loisirs', 'lavington', 'Vente de vin français', 'Bonne adresse Vente de vin français à Lavington.', '+254116222244', '+254116222244', NULL, NULL, 'en ligne', '{"Anglais"}', TRUE, 4.8, 35, '{"Vente de vin français", "Gastronomie", "Sortir", "Lavington"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Sortir à Nairobi'),
  ('sortir_49', 'D''s Place - Gaufres & Crêpes', 'loisirs', 'westlands', 'Restaurant / Café', 'Gaufrerie & crêperie', '+254727755571', '+254727755571', NULL, 'www.instagram.com/dsplace.nairobi', 'Broadwall Mall, Ojijo Road & Muthithi Road', '{"Anglais"}', TRUE, 4.8, 35, '{"Restaurant / Café", "Gastronomie", "Sortir", "Westlands"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, 'Gaufrerie & crêperie', 'Sortir à Nairobi'),
  ('admin_2', 'Ambassade de France', 'autres', 'gigiri', 'Contact visas embassade de France :', 'Service administratif & légal (Contact visas embassade de France :)', 'visas.nairobi-amba@diplomatie.gouv.fr', NULL, 'visas.nairobi-amba@diplomatie.gouv.fr', NULL, NULL, '{"Français", "Anglais"}', TRUE, 5.0, 20, '{"Démarches", "Visa", "Officiel", "Ambassade"}', 'Ambassade', 'embassy_list', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Visa Ambassade Work Permit'),
  ('admin_3', 'Alliance française', 'autres', 'lavington', 'Traduction', 'Service administratif & légal (Traduction)', '+254795753575', '+254795753575', 'translation3@afkenya.org', NULL, NULL, '{"Français", "Anglais"}', TRUE, 5.0, 20, '{"Démarches", "Visa", "Officiel", "Ambassade"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Visa Ambassade Work Permit'),
  ('admin_4', 'ABC expat', 'autres', 'lavington', 'Aide Administratif kenyan', 'Service administratif & légal (Aide Administratif kenyan)', '+254 700 000 000', NULL, NULL, NULL, NULL, '{"Français", "Anglais"}', TRUE, 5.0, 20, '{"Démarches", "Visa", "Officiel", "Ambassade"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Visa Ambassade Work Permit'),
  ('admin_5', 'Rhoda', 'autres', 'lavington', 'Work Permit', 'Service administratif & légal (Work Permit)', '+254704609894', '+254704609894', NULL, NULL, NULL, '{"Français", "Anglais"}', TRUE, 5.0, 20, '{"Démarches", "Visa", "Officiel", "Ambassade"}', 'WhatsApp Verified', 'whatsapp_group', '2026-09-01T20:25:00.000Z', 'Recommandé par un membre', 'Marie Élodie C.', 5, '', 'Visa Ambassade Work Permit')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category_id = EXCLUDED.category_id, neighborhood_id = EXCLUDED.neighborhood_id, specialty = EXCLUDED.specialty, description = EXCLUDED.description, phone = EXCLUDED.phone, whatsapp = EXCLUDED.whatsapp, email = EXCLUDED.email, website = EXCLUDED.website, address = EXCLUDED.address, languages = EXCLUDED.languages, is_verified = EXCLUDED.is_verified, rating = EXCLUDED.rating, reviews_count = EXCLUDED.reviews_count, tags = EXCLUDED.tags, source_badge = EXCLUDED.source_badge, source_channel = EXCLUDED.source_channel, source_uploaded_at = EXCLUDED.source_uploaded_at, contributor_masked = EXCLUDED.contributor_masked, contributor_revealed = EXCLUDED.contributor_revealed, reliability_score = EXCLUDED.reliability_score, original_notes = EXCLUDED.original_notes, source_sheet = EXCLUDED.source_sheet;